### ISSUE TITLE
Lots of grass in objects / Raycasting not working

### ISSUE THREAD

**Issue by eggdropsoap** [SaneEngineer/No-Grass-In-Objects-NG#9]
Grass is generating inside objects.

Versions: 

* NGIO NG: 1.0.8 AE
* Skyrim.exe: 1.6.640

## Issue description

I have already generated a throwaway grass cache successfully as a test, and then removed it. I'm now trying to properly configure my grass before generating a real grass cache, but I can't get grass to stop generating in objects.

NGIO NG is running. I am not using cached grass while I tune the raycasting, but the raycasting settings seem to do nothing and no grass is being removed from under/inside objects.

skse64.log shows NGIO NG is running:
```log
loading plugin "NGIO-NG"
registering plugin listener for SKSE at 50 of 107
plugin NGIO-NG.dll (00000001 NGIO-NG 01000000) loaded correctly (handle 50)
```

I'm using Seasons of Skyrim, Seasonal Landscapes, and Landscape Fixes for Grass Mods.

I also tested with seasons turned off (`Season Type = 0` in po3_SeasonsOfSkyrim.ini) and Landscape Fixes for Grass Mods disabled, and the grass generation in/under objects was much more obvious and worse.

This screenshot taken at the ruined house west of Whiterun (Tamriel cells -2,-3 / -2,-2) with Seasons set to 0 and Landscape Fixes disabled as above shows the generation and clipping problem clearly:

![Grass clipping through floor of ruined house west of Whiterun](https://github.com/SaneEngineer/No-Grass-In-Objects-NG/assets/3902493/14ba8d8d-b1a3-4be2-b959-c09367a9e3a1)

### GrassControl.toml

```toml
[Debug]
Debug-Log-Enable = true
  
[RayCastConfig]
Ray-cast-enabled = true 
Ray-cast-height = 150.0
Ray-cast-depth = 5.0
Ray-cast-collision-layers = "1 2 13 20 31"
Ray-cast-ignore-forms = ""

[GrassConfig]
Super-dense-grass = false
Super-dense-mode =  8
Profiler-report = false
Use-grass-cache = false
Extend-grass-distance = false
Extend-grass-count = true
Ensure-max-grass-types-setting = 10
Overwrite-grass-distance = 6000
Overwrite-grass-fade-range = 3000
Overwrite-min-grass-size = -1
Global-grass-scale = 1.0
Only-load-from-cache = false
Skip-pregenerate-world-spaces = "DLC2ApocryphaWorld;DLC01Boneyard;WindhelmPitWorldspace"
Only-pregenerate-world-spaces = ""
DynDOLOD-Grass-Mode = 1
```

### NGIO-NG.log

```log
[13:06:20:721] NGIO-NG v1.0.0.1
[13:06:20:721] Game version : 1-6-640-0
[13:06:20:721] Initializing trampoline...
[13:06:20:721] Default Trampoline => 0B / 2048B (00.00%)
[13:06:20:721] Trampoline initialized.
[13:06:20:721] Default Trampoline => 14B / 2048B (00.68%)
[13:06:28:137] Default Trampoline => 92B / 2048B (04.49%)
[13:06:28:137] Default Trampoline => 106B / 2048B (05.18%)
[13:06:28:137] Default Trampoline => 181B / 2048B (08.84%)
[13:06:28:137] Default Trampoline => 195B / 2048B (09.52%)
[13:06:55:103] Created Cache for Raycasting Settings
```
